// Navigation configuration
const navigationConfig = [
  { label: 'Home', path: '/' },
  { label: 'Dashboard', path: '/dashboard' },
  { label: 'Alerts', path: '/alerts' },
  { label: 'Services', path: '/services' },
  { label: 'Inventory', path: '/inventory' },
  { label: 'Marketplace', path: '/marketplace' },
  { label: 'Communities', path: '/communities' },
  { label: 'Impact', path: '/impact' },
  { label: 'Knowledge', path: '/knowledge' },
  { label: 'Governance', path: '/governance' },
  { label: 'Resilience', path: '/resilience' },
  { label: 'Wellness', path: '/wellness' },
  { label: '🧘‍♀️ Wellness Intelligence', path: '/wellness-dashboard' },
  { label: '🧾 Wellness Intake', path: '/wellness-intake' },
  { label: '🌿 Herbal Library', path: '/herbal-library' },
  { label: 'Expansion', path: '/expansion' },
  { label: 'Seed Bank', path: '/seedbank' },
  { label: 'Global Network', path: '/global-network' },
  { label: 'Harvest Forecast', path: '/harvest-forecast' },
  { label: 'Pest Management', path: '/pest-management' },
  { label: 'Water Recycling', path: '/water-recycling' },
  { label: 'Aquatic Life', path: '/aquatic-life' },
  { label: 'Autopilot Mode', path: '/autopilot' },
  { label: 'Nutrition Optimization', path: '/nutrition-optimization' },
  { label: 'Climate Settings', path: '/climate-settings' },
  { label: 'Plugins', path: '/plugins' },
  { label: 'Sustainability', path: '/sustainability' },
  { label: '📡 IoT Sensors', path: '/iot' },
  { label: '🌍 Impact Dashboard', path: '/impact-tracking' },
  { label: '🔮 Predictions', path: '/predictions' },
  { label: 'Settings', path: '/settings' },
  { label: 'Admin', path: '/admin' },
];

export default navigationConfig;
